language: objective-c
osx_image: xcode9
xcode_project: TORoundedTableViewExample.xcodeproj
xcode_scheme: TORoundedTableViewExampleTests
script: xcodebuild -verbose -scheme TORoundedTableViewExampleTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' test
